language: java
jdk: oraclejdk8
dist: trusty
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
env:
  global:
  - SIGN_KEY_ID=CDE3528F
  - SIGN_SECRET_KEY_RINGFILE=secring_xenit.gpg
before_install:
- chmod +x ./gradlew
script:
- "./gradlew check"
deploy:
    - provider: script
      script:
        - "echo $key_passphrase | gpg --passphrase-fd 0 secring_xenit.gpg.gpg && ./gradlew publish"
      skip_cleanup: true

      on:
        branch: release
    - provider: script
      script:
        - "./gradlew publish"
      skip_cleanup: true
      on:
        branch: master