language: java
jdk: oraclejdk8
dist: trusty
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    env:
    - PUBLISH_USER=xenit
    - SIGN_KEY_ID=CDE3528F
    - SIGN_SECRET_KEY_RINGFILE=secring_xenit.gpg
    before_install:
    - chmod +x ./gradlew
    - openssl aes-256-cbc -K $encrypted_3472f6e1405d_key -iv $encrypted_3472f6e1405d_iv
      -in secring_xenit.gpg.enc -out secring_xenit.gpg -d
    script:
    - "./gradlew check"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
env:
  global:
    - secure: GqvBMdx5W4TQ83OuqX9ffAsjLc505N1ZZXORY6fNsomhM1PWo/igPWzDhvOask3GsEiBMH+LGEDAMbh8li/v23lalyhe5S02UFw5TunGpWNhJ7wHn0tKXeG9OG1Ly4ywfAWeXC3kR8U3N9nblefO8c7Jt/5wwEtRNQpEZrNBi78u3VdIi9EoPRzmf87+kYsm1NANhLoUYj2HUIPqvhJKzGOnUvxt2flwzcMNvadTNDc1bgrzPc90OmeCEhRezBMCDfBsVW31DXQdpIMT6JEVjQPg4i7BDTeahdtaYKcOG88JcQr/07zOLBLqax+hCoKmmXjydQPhkziBWZ9w+9e5MbiLwrpIKA7jGRXkykfB3SFyGa17m6jrat5oBw9rtlEWctizULinSKy3AJBqUVwf9y0JyyggNJi53DIcdzUPxnxu3ktxaH4KRloQTT0xSJ5ba5oi9POQAOxd6r6TMHYcBolJIfRbRGw4uV90igueiSaei4SMLHr1AJvpJMsUA0/R+hwZufwngq3SsGVnHuh3wwd3okMdKCYbwOpr4c0C3QNKycsjBaJnJgnTJTe8vGuJhxGpj19hHYS022sa8yHT/QOZQVoHwPZBg1AD+2lLh0d0Wcw5gcXt0cJQILlM0Ly+AyF168b78Yq101x5bNBz3kljdzd59SumANjMoKT7ui8=
    - secure: gkF3HQv8YoffcrZ+r3gbT3UK7MTh93fno7W2/8E8AZ8LSXiatP6URL2GaUei7zXi7vj7FuxMyu+FA+348KmGOlxHXLBrUzHV1QjYRjwpYygMbU/c861VBNk2J92Y4yRcJ4MuE/JNxJABqwu5SNt7IQuEB1DcILJyCeptZnWFDK658XYOuiDb5JaQ/oYeqm8mNX6SHKHYcI2BovN9oATd1pZrYt5mGCIInqiAEnnlTuEG9HYcKjgXP3EQgxSeWsgBjbSdpPsjOwVNL+OwjM0wanK3GhYlOB5vNGY4ZzmtcvgJ4ADVNJITKCHn4F9VT6Img3i2MAJLZdI0Ez3r/jWUmFb0P0R0Q41KDD1Jx5EETkbciXDcOYIq9XeIjCl8VOIWRaC3aGacfG3nn7L5i2/58Z6SwyIwGjrHGA3ygL6yy5AryFcusG63clFq3vQsthkUgNns6+X5WvmnC97Jt8Ab2Y0ZNeDYdA9eEBj2s21tdftbkpYwLDaFTROaXMbXvz7dyzxiZ1BW/e1sBPzvhGVo6NIhxkF76g1VqEngFxgQwlRwtNwR6DqExiVrF2+d48kQ8CGf0HBowcIC4gqNnKRJLSo/QyElZXJRaK8iM+HDJ442qZthm0Cl/IP/y6ioZbqmwHDjku7XV5twW2Cm8uUTn0/r8fFKCmZrglcvC6/CbiY=
    - secure: gyTt/ejcD6+kzmVJYsMkhs4gtEnCAjKO39ZN5zrN32oROYzn2lsMxqTbF/p+MIjZme5OqyL+MIkvSLkt+C06PaE8GpAnYGOw9/RejJ4s8rXLihA96DvgN3rqEr4h2VnWE78su75eH2Fxyy2PhnGqeA+P+LsN4hBjlSGrQ60R+Qfn36iNjX1upnle6vkU4PFcdtyCvUkJMnj9KfzXMnGJ8n74Iivk0tebM/nFT+Jdjy+m7E1LsAQvxi5/GezUUVozQaPnmWNC8WQw5N+HiW7CPV1XZVEIpbyZd0qe8ZQ/wp/bLtV/pd4F+tqv78sLpqBtRYIGW/XuiG9+7s7hY+SCkQ0A3ay5jyOZdDsSumLztLWS1ZsAvv4sI2xKG+cB+ofzfRND/NoBF+a7E2iyLocTTt66MVqdjqP11b8X34KbuizmDIDLF3pLAu4Dp80TvsaM274JZ/8bt9V8iiJkeehNh/hh+4PVTuWDOLcLnJr7etxBt/qCzu9/tp07+4wMnCKHPQaCPaoDSyhCP8uHuLoeyuBxSTR6CHbjCjqplZtNOnrDm78QAj0UaW6HarUPp/Ran9cvijj+we6j9b1D3wbwcm7ym38QxKWCxdWBU9V1ydF7czHdOpGrSvaPZARChtim9Kwqq2pCsRo1z5oI0FGMsGSTJ6MoA35JZdtaYUb1oQ0=
    - secure: eRo1kDuW4PMmi64oAg3oFPSyBB1g/hqFOWz7wRco8Wq3cstIrixGcGoqFvUUC0dBNavoVaurdgKpI0hzWARgVbwqnle6vdQg1olKxvwAo95J6hC4UoNXnB8IAy7QuEiJ21ULwY8px5zvLG6YiFaldDPQFrRmLHHk8ahbETiPkS/uSE1VueMWddFQMtKG5ISX4gu6cjhrKpS0JRBZUpKGy1lo8ONdExLE8iMafe2YwvnyrOGmDoCzznlTd/jTlYJaQQVd70noIXDDUw+E+FAAQzI57aH7Tix3z+kCSGnULHMhAK5m27MofstHnppPT00XdhDJgFms3pFrykFyoOEHgosdsX2c3fiJK+VJk0PFnkLcK3V6xL8qVxFPzHyxHPoEZoZxz2hRS0hRCwzthPGcSlKoWKXrDFt0DYv+cPgglydBTOapjMUmvvRsGtmIMS9nbEDQA7wNonePZroo/6r/XyW5++LJzORNhZPFi8qZdPcgJIG8vcTk0ZRhvhXcM7vTJ+ZeqboxiZ88U6gy/qwC/+ZEh9tUaAgwnxP4zLjhE97JLlGwWdEbCui8PsG5dlU252l7t3cG5mnv3YC6OMhDthfGatfBeyX3deCYg2WWL5Dz813NpD2gVnFMQyRy/QYySMRae1sisfB8BLARr673KJcX32dGms4DiLO5M4NRcHY=

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
  script: "./gradlew publish"
