name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: ./gradlew check
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-build
          path: build/reports
      - name: Upload analysis to sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_Arender4Alfresco -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
        run: ./gradlew publish
